config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "ideas#index"

  resources :ideas, only: [:index, :create, :new, :show] do
    resources :comments, only: [:create]
    resources :joins, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
  

  #---CLASS METHODS------------------
  #display most recent comments first
  def self.most_recent_comments
    Comment.order("created_at DESC")
  end


end

app/models/idea.rb
class Idea < ActiveRecord::Base
  #--ASSOCIATIONS-----------------------
  has_many :comments, dependent: :destroy
  belongs_to :user

  #many to many for 'joins' (or members)
  has_many :joins, dependent: :destroy
  has_many :users_who_joined, through: :joins, source: :user

  #many to many for likes
  has_many :likes, dependent: :destroy
  has_many :users_who_liked, through: :likes, source: :user

  #---VALIDATIONS-------------------------
  validates :title, uniqueness: true

   #--FOR ATTACHING IMAGES w/ PAPERCLIP--------------
  has_attached_file :picture, :styles => { :medium => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  #--VALIDATIONS--------------------------------------
  #combination of user and idea must be unique
  validates :user_id, uniqueness: {scope: :idea_id}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  #--VALIDATIONS----------------------
  #combination of user and idea must be unique
  validates :user_id, uniqueness: {scope: :idea_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  #--ASSOCIATIONS------------------------------
  has_many :ideas, dependent: :destroy
  has_many :comments, dependent: :destroy

  #many to many for joins/member ideas
  has_many :joins, dependent: :destroy
  has_many :ideas_joined, through: :joins, source: :idea

  #many to many for likes
  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)
    @idea = Idea.find(params[:idea_id])
    @comment.idea = @idea

    if @comment.save
      redirect_to @idea, notice: "Comment Added!"
    else
      render "/ideas/show"
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController


  def index
    #show all of the ideas on this page
    @ideas = Idea.all

    #for the jquery form
    @idea = Idea.new
  end


  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      redirect_to root_path, notice: "Idea Created!"
    else
      render :new
    end
  end


  def new
    @idea = Idea.new

  end


  def show
    @idea = Idea.find(params[:id])

    #instantiate a new commment to be created
    @comment = Comment.new

    #this will dispaly the most recent comments first
    @comments = @idea.comments.most_recent_comments
  end


  private

  def idea_params
    params.require(:idea).permit(:title, :body, :picture)
  end


end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  #join an idea
  def create
    join = current_user.joins.new
    idea = Idea.find(params[:idea_id])
    join.idea = idea

    if join.save
      redirect_to root_path, notice: "Joined Idea!"
    else
      redirect_to root_path, alert: "Join didn't work..."
    end

  end

  #unjoin an idea
  def destroy
    join = Join.find(params[:id])
    join.destroy
    redirect_to root_path, notice: "unjoined idea"
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  #like an idea
  def create
    like = current_user.likes.new
    idea = Idea.find(params[:idea_id])
    like.idea = idea

    if like.save
      redirect_to root_path, notice: "idea liked!"
    else
      redirect_to root_path, alert: "like didn't work..try again"
    end
  end


  #unlike an idea
  def destroy
    like = Like.find(params[:id])
    like.destroy
    redirect_to root_path, alert: "unliked!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/ideas/_form.html.erb
<%#--FORM TO CREATE A NEW IDEA--------------------------%>
<div class="create-project-form">
    <%= form_for @idea do |f| %>
      <%= f.text_field :title, {class: "form-control", placeholder: "Your super-amazing Idea Title here..." } %>
      <br>
      <%= f.text_area :body, {class: "form-control", rows: "10", placeholder: "All the details about your awesome idea here..."} %>
      <br>
      Add An Image: <%= f.file_field :picture %>
      <br>
      <%= f.submit "Submit Awesome Idea!" %>
    <% end %>
</div>

app/views/ideas/index.html.erb
<h1>Welcome to The Idea Factory!</h1>
<%#---BUTTON TO MAKE A NEW FORM ----------------------------------------%>
  <button class="new-idea btn btn-danger">Create A New Idea</button> 
  <br>
  <br>

  <%#--FORM TO CREATE A NEW IDEA **HIDDEN BY JQUERY--------------------------%>
  <div class="create-project-form">
    <%= form_for @idea do |f| %>
      <%= f.text_field :title, {class: "form-control", placeholder: "Your super-amazing Idea Title here..." } %>
      <br>
      <%= f.text_area :body, {class: "form-control", rows: "10", placeholder: "All the details about your awesome idea here..."} %>
      <br>
      Add An Image: <%= f.file_field :picture %>
      <br>
      <%= f.submit "Submit Awesome Idea!" %>
    <% end %>
    <br>
    <br>
  </div>




<%#--VIEW ALL OF THE OTHER IDEAS-------------------------------------%>
<h2>All Ideas</h2>
<hr>

<% @ideas.each do |idea| %>
  <h3><%= idea.title %></h3>
  <br>
  Idea Details: <%= idea.body %>
  <br>
  By: <%= idea.user.first_name %>
  <br>
  <%= link_to "View This Idea", idea %>
  <br>

      <%#---FOR JOINING & LIKING AN IDEA--------------------------------------------%>
      <%# users cannot join an idea that they created. Hide those buttons in this case %>
      <% if idea.user.id != current_user.id %>
            <%# see if the user has already joined this idea %>

            <%#--FOR JOINING AN IDEA-----------------------------------------%>
            <% join = idea.joins.find_by_user_id(current_user.id) %>
            <% if join %>
                <%= link_to "Already Joined", idea_join_path(idea, join), method: :delete, class: "btn btn-success" %>
            <% else %>
                <%= link_to "Join", idea_joins_path(idea), method: :post, class: "btn btn-success" %>
            <% end %>
            <br>

            <%#--FOR LIKING AN IDEA---------------------------------------------%>
            <% like = idea.likes.find_by_user_id(current_user.id) %>
            <% if like %>
                <%= link_to "Unlike", idea_like_path(idea, like), method: :delete, class: "btn btn-success" %>
            <% else %>
                <%= link_to "Like", idea_likes_path(idea), method: :post, class: "btn btn-success" %>
            <% end %>


      <% end %>
      <br>

   
  <%#---SHOW THE AMOUNT OF LIKES / MEMBERS -------------------------------------%>
  Members: <%= idea.users_who_joined.count %>  |
  Likes:  <%= idea.likes.count %>


  <hr>
<% end %>

app/views/ideas/new.html.erb
<h1>Create A New Idea!</h1>

<%= render "form" %>

app/views/ideas/show.html.erb
<h1>Showing Idea:</h1> 
<h2><%= @idea.title %></h2>
<br>
<%= image_tag @idea.picture.url(:medium) %>
<p><%= @idea.body %></p>
<p>Created By: <%= @idea.user.first_name%></p>
<br>

<%#--View People who've joined this idea ----- %>
<h3>People Who Have Joined this Project:</h3>
<% @idea.users_who_joined.each do |user| %>
  <%= user.first_name %>
  <br>
  <hr>
<% end %>

<hr>

<br>
<br>

<h3>Comments:</h3>
<% @comments.each do |comment| %>
  <%= comment.body %>
  <br>
  By: <%= comment.user.first_name %>
  <br>
  <hr>
<% end %>

<h3>Add A Comment To This Idea</h3>

<%# form to create a new commment-----------%>
<%= form_for @comment, url: idea_comments_path(@idea) do |f| %>
  <%= f.text_area :body, placeholder: "Your Comment Here...keep it clean!" %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaFactory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
      <br>
      <%= link_to "All Ideas", root_path %>
      <%#--only if the user is signed in----------------------------------------------%>
      <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, style: "float: right" %> 
            <span style="float: right">Hello <%= current_user.first_name %> | </span>
      <% end %>
      <br>

      <%#--FLASH MESSAGES--------------------------------%>
      <%# use the nice alerts from bootstrap based on different cases %>
        <% if flash[:notice] %>
          <p class="alert alert-success"><%= flash[:notice] %></p>
        <% elsif flash[:alert] %>
          <p class="alert alert-danger"><%= flash[:alert] %></p>
        <% end %>

      <%#--PAGE CONTENT----------------------------------------%>
      <%= yield %>
  </div>


</body>
</html>